CREATE TABLE IF NOT EXISTS queue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(255) NOT NULL,
  uuid VARCHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS event (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid VARCHAR(36) NOT NULL,
  queue_id INT NOT NULL,
  title VARCHAR(255),
  author VARCHAR(255),
  content BLOB,
  created BIGINT NOT NULL
);
